# evaluate_utils.py (corrected)
import sys
import os
import torch
import numpy as np
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt
from matplotlib.colors import TwoSlopeNorm
from matplotlib.patches import Rectangle
from typing import List, Tuple, Optional, Any
from tqdm import tqdm
from Bio.PDB import PDBParser
from Bio.PDB.PDBList import PDBList
from Bio.SeqUtils import seq1
from esm import pretrained, Alphabet
import subprocess
import glob
import shlex
import shutil

# ensure local utilities path
sys.path.append('/sci/labs/orzuk/meirab/stability_algo/weight0/stability_utils')
from esm_utils import *


# canonical AA_ORDER used everywhere (20 canonical AA)
AA_ORDER = ["A","R","N","D","C","Q","E","G","H","I","L","K","M","F","P","S","T","W","Y","V"]

def read_design_seq_from_file(pdb_id: str,weight_exp: str):
    """Prefer design sequence txt file generated by your pipeline."""

    fn = f"/sci/labs/orzuk/meirab/stability_algo/beam_outputs/{pdb_id}_beam_best_{weight_exp}.txt"
    if not os.path.exists(fn):
        return None
    with open(fn, "r") as fh:
        s = fh.read().strip().upper()
    s = "".join(s.split())
    return s if s else None

def read_design_seq_from_pdbfile(pdb_path: str, chain: str = "A"):
    if not os.path.exists(pdb_path):
        return None
    try:
        seq = extract_sequence_from_pdb(pdb_path, chain)
        return seq
    except Exception:
        return None

def run_pymol_overlay(overlay_pml: str, wt_pdb: str, design_pdb: str, out_png: str):
    """
    Runs PyMOL overlay command similar to your example:
    pymol -cq overlay.pml -- wt_pdb design_pdb overlay_out.png
    """
    cmd = ["pymol", "-cq", overlay_pml, "--", wt_pdb, design_pdb, out_png]
    print(f"[INFO] Running PyMOL: {' '.join(cmd)}")
    try:
        subprocess.run(cmd, check=True)
        print(f"[DONE] PyMOL overlay saved to {out_png}")
    except subprocess.CalledProcessError as e:
        print(f"[ERROR] PyMOL overlay failed: {e}")

def save_summary(outdir: Path, summary: dict):
    out = outdir / "evaluation_summary.txt"
    with open(out, "w") as fh:
        for k, v in summary.items():
            fh.write(f"{k}: {v}\n")
    print(f"[INFO] Wrote summary to {out}")


def _ensure_pdb_unzipped(pdb_file: str) -> str:
    """
    PDBList may return a .pdb or .pdb.gz path. Biopython's PDBParser
    can handle gz, but keep this helper to strip .gz if needed (or leave).
    """
    return pdb_file

def fetch_and_extract_sequence(pdb_id: str, chain_id: str = "A") -> str:
    pdb_id = pdb_id.lower()
    pdbl = PDBList()
    pdb_file = pdbl.retrieve_pdb_file(pdb_id, pdir="pdb_cache", file_format="pdb")
    pdb_file = _ensure_pdb_unzipped(pdb_file)

    parser = PDBParser(QUIET=True)
    structure = parser.get_structure(pdb_id, pdb_file)
    model = structure[0]

    if chain_id not in model:
        raise ValueError(f"Chain {chain_id} not found in downloaded PDB {pdb_id}")

    chain = model[chain_id]
    residues = [res for res in chain if res.get_id()[0] == " "]
    seq = "".join(seq1(res.get_resname()) for res in residues)
    return seq


def extract_sequence_from_pdb(pdb_path: str, chain_id: str = "A") -> str:
    parser = PDBParser(QUIET=True)
    structure = parser.get_structure("design", pdb_path)
    model = structure[0]

    if chain_id not in model:
        raise ValueError(f"Chain {chain_id} not found in {pdb_path}")

    chain = model[chain_id]
    residues = [res for res in chain if res.get_id()[0] == " "]
    seq = "".join(seq1(res.get_resname()) for res in residues)
    return seq


def load_esm1v_model(device: Optional[str] = None):
    """
    Load ESM-1v model and alphabet and move model to `device`.
    Returns (model, alphabet). Defaults to cuda if available else cpu.
    """
    from esm.pretrained import load_model_and_alphabet
    if device is None:
        device = "cuda" if torch.cuda.is_available() else "cpu"
    os.environ["TORCH_HOME"] = "/sci/labs/orzuk/meirab/stability_algo/torch_cache"
    model, alphabet = load_model_and_alphabet("esm1v_t33_650M_UR90S_1")
    model.eval()
    model = model.to(device)
    return model, alphabet


def validate_design_ddg(wt_seq: str, design_seq: str, model, alphabet, output_csv: str) -> pd.DataFrame:
    """
    Compute DDG for all single mutations on WT and Design backgrounds.
    Writes a CSV with columns:
      pos, mut, wt_ref, design_ref, mutation_wt, mutation_design, ddg_wt, ddg_design, delta
    NOTE: uses compute_ddg_mutation(...) which computes a single mutation ddg.
    """
    assert len(wt_seq) == len(design_seq), "Sequences must be the same length"
    L = len(wt_seq)
    rows = []

    for i in range(L):
        pos = i + 1
        wt_ref = wt_seq[i]
        design_ref = design_seq[i]

        for aa in AA_ORDER:
            # ddg on WT background
            if aa == wt_ref:
                ddg_wt = np.nan
            else:
                ddg_wt = compute_ddg_esm1v(wt_seq, pos, model, alphabet)

            # ddg on design background
            if aa == design_ref:
                ddg_design = np.nan
            else:
                ddg_design = compute_ddg_esm1v(design_seq, pos, model, alphabet)

            rows.append({
                "pos": pos,
                "mut": aa,
                "wt_ref": wt_ref,
                "design_ref": design_ref,
                "mutation_wt": f"{wt_ref}{pos}{aa}",
                "mutation_design": f"{design_ref}{pos}{aa}",
                "ddg_wt": ddg_wt,
                "ddg_design": ddg_design,
                "delta": (ddg_design - ddg_wt) if (not np.isnan(ddg_design) and not np.isnan(ddg_wt)) else np.nan
            })

    df = pd.DataFrame(rows)
    df["mutation"] = df["mutation_wt"]
    df.to_csv(output_csv, index=False)
    return df


def convert_fasta_to_a3m(msa_fasta: Path, msa_a3m: Path):
    """
    Minimal FASTA?A3M conversion: strip insertions and write in A3M format.
    """
    with open(msa_fasta) as fin, open(msa_a3m, "w") as fout:
        seq = ""
        header = None
        for line in fin:
            if line.startswith(">"):
                if header:
                    fout.write(header + "\n")
                    fout.write(seq + "\n")
                header = line.strip()
                seq = ""
            else:
                # remove gaps/inserts if needed; here we just keep uppercase letters
                seq += "".join([c for c in line.strip() if c.isupper() or c == "-"])
        if header:
            fout.write(header + "\n")
            fout.write(seq + "\n")


def run_alphafold_colabfold(
    pdb_id: str,
    msa_fasta_path: str,
    outdir: str,
    script_path: str = "/sci/labs/orzuk/meirab/stability_algo/stability_utils/run_colabfold.sh"
) -> str:
    """
    Run ColabFold using a precomputed MSA (FASTA?A3M).
    """
    outdir = Path(outdir)
    outdir.mkdir(parents=True, exist_ok=True)

    msa_dir = outdir / "msa_input"
    msa_dir.mkdir(exist_ok=True)

    msa_fasta = Path(msa_fasta_path)
    msa_a3m = msa_dir / f"{pdb_id}.a3m"
    msa_fasta_copy = msa_dir / f"{pdb_id}.fasta"

    # Copy fasta and convert to a3m
    shutil.copy(msa_fasta, msa_fasta_copy)
    convert_fasta_to_a3m(msa_fasta, msa_a3m)

    # Submit SLURM job
    cmd = ["sbatch", script_path, str(msa_dir), str(outdir)]
    print("[INFO] Submitting ColabFold job:", " ".join(cmd))
    subprocess.run(cmd, check=True)

    # Wait for results
    pdb_file = None
    for _ in range(1000):  # ~8h max
        candidates = list(outdir.rglob("*.pdb"))
        if candidates:
            candidates = sorted(candidates, key=lambda p: p.stat().st_mtime, reverse=True)
            for c in candidates:
                if any(tag in c.name for tag in ["rank_1", "rank_001", "unrelaxed"]):
                    pdb_file = c
                    break
            pdb_file = pdb_file or candidates[0]
            break
        time.sleep(30)

    if not pdb_file:
        raise RuntimeError(f"No PDB found in {outdir} after ColabFold run.")

    print("[INFO] ColabFold predicted PDB:", pdb_file)
    return str(pdb_file)

def plot_wt_vs_design_heatmaps(
    csv_path: str,
    outfile: str = None,
    title: str = None,
    mutated_positions=None,           # Iterable of ints (positions to box)
    wt_by_pos: dict = None,           # Optional: {pos: 'A'}
    wt_seq: str = None                # Optional: WT sequence string (1-based positions)
):
    df = pd.read_csv(csv_path)
    required = {"pos", "mut", "ddg_wt", "ddg_design"}
    missing = required - set(df.columns)
    if missing:
        raise ValueError(f"CSV missing required columns: {missing}")

    df = df[df["mut"].isin(AA_ORDER)].copy()
    positions = sorted(df["pos"].unique().tolist())

    # Build WT mapping per position
    wt_map = {}
    if "wt" in df.columns:
        tmp = df.dropna(subset=["wt"]).groupby("pos")["wt"].agg(lambda x: x.mode().iat[0] if not x.mode().empty else x.iloc[0])
        wt_map = tmp.to_dict()
    elif wt_by_pos is not None:
        wt_map = dict(wt_by_pos)
    elif wt_seq is not None:
        for p in positions:
            idx = int(p) - 1
            if 0 <= idx < len(wt_seq):
                wt_map[p] = wt_seq[idx]

    # Pivot to matrices (reindex to ensure consistent ordering)
    wt_pivot = (df.pivot_table(index="mut", columns="pos", values="ddg_wt", aggfunc="mean")
                  .reindex(index=AA_ORDER, columns=positions))
    design_pivot = (df.pivot_table(index="mut", columns="pos", values="ddg_design", aggfunc="mean")
                     .reindex(index=AA_ORDER, columns=positions))

    # Shared zero-centered color scale
    vals = np.concatenate([wt_pivot.values.ravel(), design_pivot.values.ravel()])
    vals = vals[~np.isnan(vals)]
    vmax = np.percentile(np.abs(vals), 99) if vals.size else 1.0
    norm = TwoSlopeNorm(vmin=-vmax, vcenter=0.0, vmax=vmax)

    fig, axes = plt.subplots(1, 2, figsize=(16, 6), constrained_layout=True)
    if title:
        fig.suptitle(title, fontsize=14, y=1.02)

    im0 = axes[0].imshow(wt_pivot.values, aspect="auto", norm=norm)
    axes[0].set_title("DDG (WT background)")
    axes[0].set_xlabel("Position")
    axes[0].set_ylabel("Mutant AA")
    axes[0].set_xticks(range(len(positions)))
    axes[0].set_xticklabels(positions, rotation=90, fontsize=8)
    axes[0].set_yticks(range(len(AA_ORDER)))
    axes[0].set_yticklabels(AA_ORDER)

    im1 = axes[1].imshow(design_pivot.values, aspect="auto", norm=norm)
    axes[1].set_title("DDG (Design background)")
    axes[1].set_xlabel("Position")
    axes[1].set_ylabel("")
    axes[1].set_xticks(range(len(positions)))
    axes[1].set_xticklabels(positions, rotation=90, fontsize=8)
    axes[1].set_yticks(range(len(AA_ORDER)))
    axes[1].set_yticklabels(AA_ORDER)

    # Boxes for mutated positions
    if mutated_positions is None:
        mutated_positions = []
    # mutated_positions is a list like ["G1M", "A34T", ...]
    def extract_pos(mut_str):
        # Extract digits from something like "G1M"
        return int("".join([c for c in mut_str if c.isdigit()]))

    mutated_positions = set(extract_pos(p) for p in mutated_positions)

    for p in mutated_positions:
        x = positions.index(p)
        rect_wt = Rectangle((x - 0.5, -0.5), 1.0, len(AA_ORDER), fill=False, edgecolor="black", linewidth=1.8)
        rect_ds = Rectangle((x - 0.5, -0.5), 1.0, len(AA_ORDER), fill=False, edgecolor="black", linewidth=1.8)
        axes[0].add_patch(rect_wt)
        axes[1].add_patch(rect_ds)

    # mark WT cells with 'x' if NaN
    for p in positions:
        wt_aa = wt_map.get(p, None)
        if wt_aa is None or wt_aa not in AA_ORDER:
            continue
        y = AA_ORDER.index(wt_aa)
        x = positions.index(p)
        if np.isnan(wt_pivot.iloc[y, x]):
            axes[0].scatter([x], [y], marker='x', s=30, c='black', linewidths=1.2, zorder=3)
        if np.isnan(design_pivot.iloc[y, x]):
            axes[1].scatter([x], [y], marker='x', s=30, c='black', linewidths=1.2, zorder=3)

    cbar = fig.colorbar(im1, ax=axes.ravel().tolist(), shrink=0.9, pad=0.02)
    cbar.set_label("DDG (negative = more stable)")

    if outfile:
        plt.savefig(outfile, dpi=300, bbox_inches="tight")
        plt.close(fig)
    else:
        plt.show()
